[package]
name = "blazen"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = "z"
lto = true

[dependencies]
constgebra = "0.1.4"
heapless = "0.8.0"
libm = "0.2.11"
strum = { version = "0.26.3", features = ["derive"] }
wasm4 = { version = "0.2.0", features = ["include-sprites"] }
